function ALLEEG = p1_cleanline(ALLEEG, cfg)
% Remove line noise at US power-line harmonics using the CleanLine plugin.
%
% Targets cfg.cleanline_hz (default [60 120 180] Hz for 60 Hz countries).
% CleanLine fits and subtracts sinusoidal components without affecting
% broadband signal, which is preferable to a notch filter for ERSP analysis.
%
% Key parameters justified:
%   winsize/winstep = 4 s: balances frequency resolution and stationarity.
%   bandwidth = 2 Hz: narrow enough not to smear adjacent bands.
%   p = 0.01: conservative detection threshold; reduces false removals.
%   scanforlines = 1: lets CleanLine search nearby frequencies in case
%       the actual line drifts slightly from the nominal value.
%
% Requires: CleanLine plugin (EEGLAB plugin manager or manual install).

cleanline_opts = { ...
    'bandwidth',     2, ...
    'chanlist',      [], ...   % [] = all channels
    'computepower',  0, ...
    'linefreqs',     cfg.cleanline_hz, ...
    'normSpectrum',  0, ...
    'p',             0.01, ...
    'pad',           2, ...
    'plotfigures',   0, ...
    'scanforlines',  1, ...
    'sigtype',       'Channels', ...
    'tau',           100, ...
    'verb',          0, ...
    'winsize',       4, ...
    'winstep',       4 };

for i = 1:length(ALLEEG)
    ALLEEG(i) = pop_cleanline(ALLEEG(i), cleanline_opts{:});
    fprintf('[p1_cleanline] Subject %s: line noise removed at %s Hz.\n', ...
        ALLEEG(i).subject, num2str(cfg.cleanline_hz));
end
end
